before:
  hooks:
    - go mod download
build:
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
